### ISSUE TITLE
not working with go1.1

### ISSUE THREAD

**Issue by kishorevaishnav** [alouche/rodent#5]
I couldn't get it working for go1.1 ...  here are the errors
I am using MacOS 10.9.5.

```
~/gothings/src/test_rodent/rodent1 
20:46 $ rodent install go1.1
# Downloading golang source go1.1
# Untarring binary to /Users/kishore/rodent/releases
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
libmach
misc/pprof
..
..
..
testing/iotest
testing/quick
# runtime/cgo
clang: warning: argument unused during compilation: '-pthread'
# runtime/cgo
clang: error: no such file or directory: 'libgcc.a'
error: compilation failed - installation aborted
```
